// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relayer.proto

package relayer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WithdrawRequest struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	RollupBlockNumber    int64    `protobuf:"varint,2,opt,name=rollupBlockNumber,proto3" json:"rollupBlockNumber,omitempty"`
	TransitionIndex      int64    `protobuf:"varint,3,opt,name=transitionIndex,proto3" json:"transitionIndex,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawRequest) Reset()         { *m = WithdrawRequest{} }
func (m *WithdrawRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawRequest) ProtoMessage()    {}
func (*WithdrawRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{0}
}

func (m *WithdrawRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawRequest.Unmarshal(m, b)
}
func (m *WithdrawRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawRequest.Merge(m, src)
}
func (m *WithdrawRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawRequest.Size(m)
}
func (m *WithdrawRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawRequest proto.InternalMessageInfo

func (m *WithdrawRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *WithdrawRequest) GetRollupBlockNumber() int64 {
	if m != nil {
		return m.RollupBlockNumber
	}
	return 0
}

func (m *WithdrawRequest) GetTransitionIndex() int64 {
	if m != nil {
		return m.TransitionIndex
	}
	return 0
}

func (m *WithdrawRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type WithdrawResponse struct {
	TransactionHash      string   `protobuf:"bytes,1,opt,name=transactionHash,proto3" json:"transactionHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawResponse) Reset()         { *m = WithdrawResponse{} }
func (m *WithdrawResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawResponse) ProtoMessage()    {}
func (*WithdrawResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{1}
}

func (m *WithdrawResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawResponse.Unmarshal(m, b)
}
func (m *WithdrawResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawResponse.Merge(m, src)
}
func (m *WithdrawResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawResponse.Size(m)
}
func (m *WithdrawResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawResponse proto.InternalMessageInfo

func (m *WithdrawResponse) GetTransactionHash() string {
	if m != nil {
		return m.TransactionHash
	}
	return ""
}

func init() {
	proto.RegisterType((*WithdrawRequest)(nil), "relayer.WithdrawRequest")
	proto.RegisterType((*WithdrawResponse)(nil), "relayer.WithdrawResponse")
}

func init() { proto.RegisterFile("relayer.proto", fileDescriptor_202a89775a80bd4c) }

var fileDescriptor_202a89775a80bd4c = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x45, 0x94, 0x9e, 0x40, 0x05, 0x4f, 0x06, 0x31, 0x54, 0x99, 0x22, 0xd4, 0x26,
	0x12, 0xac, 0x2c, 0x74, 0x82, 0x05, 0x24, 0x2f, 0x48, 0x6c, 0x8e, 0x7b, 0x4a, 0xa2, 0xa6, 0xbe,
	0x70, 0xb6, 0x55, 0x78, 0x1c, 0xde, 0x14, 0xd1, 0x24, 0x54, 0x0a, 0x8c, 0xf7, 0x9f, 0xf5, 0xf9,
	0xbf, 0x0f, 0xce, 0x18, 0x6b, 0xfd, 0x89, 0x9c, 0x36, 0x4c, 0x9e, 0xc4, 0xb8, 0x1b, 0xe3, 0xaf,
	0x08, 0xa6, 0xaf, 0x95, 0x2f, 0x57, 0xac, 0xb7, 0x0a, 0xdf, 0x03, 0x3a, 0x2f, 0x24, 0x8c, 0xb5,
	0x31, 0x14, 0xac, 0x97, 0xd1, 0x2c, 0x4a, 0x26, 0xaa, 0x1f, 0xc5, 0x1c, 0x2e, 0x98, 0xea, 0x3a,
	0x34, 0xcb, 0x9a, 0xcc, 0xfa, 0x39, 0x6c, 0x72, 0x64, 0x79, 0x38, 0x8b, 0x92, 0x91, 0xfa, 0xbb,
	0x10, 0x09, 0x4c, 0x3d, 0x6b, 0xeb, 0x2a, 0x5f, 0x91, 0x7d, 0xb2, 0x2b, 0xfc, 0x90, 0xa3, 0xdd,
	0xdb, 0x61, 0x2c, 0xae, 0x61, 0xe2, 0xaa, 0xc2, 0x6a, 0x1f, 0x18, 0xe5, 0xd1, 0x2c, 0x4a, 0x4e,
	0xd5, 0x3e, 0x88, 0xef, 0xe1, 0x7c, 0x5f, 0xd1, 0x35, 0x64, 0x1d, 0xfe, 0xb2, 0xb5, 0xf9, 0xa1,
	0x3c, 0x6a, 0x57, 0x76, 0x5d, 0x87, 0xf1, 0xed, 0x0b, 0x80, 0x6a, 0x8f, 0x55, 0x8d, 0x11, 0x0f,
	0x70, 0xd2, 0xb3, 0x84, 0x4c, 0x7b, 0x29, 0x03, 0x03, 0x57, 0x97, 0xff, 0x6c, 0xda, 0x8f, 0xe3,
	0x83, 0xe5, 0xfc, 0xed, 0xa6, 0xa8, 0x7c, 0x19, 0xf2, 0xd4, 0xd0, 0x26, 0x33, 0x58, 0x23, 0x2f,
	0x2c, 0xfa, 0x2d, 0xf1, 0x3a, 0x2b, 0x68, 0xd1, 0x7a, 0xc8, 0x3a, 0x40, 0x7e, 0xbc, 0x13, 0x7e,
	0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x51, 0x63, 0x97, 0x90, 0x81, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RelayerRpcClient is the client API for RelayerRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RelayerRpcClient interface {
	Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error)
}

type relayerRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayerRpcClient(cc grpc.ClientConnInterface) RelayerRpcClient {
	return &relayerRpcClient{cc}
}

func (c *relayerRpcClient) Withdraw(ctx context.Context, in *WithdrawRequest, opts ...grpc.CallOption) (*WithdrawResponse, error) {
	out := new(WithdrawResponse)
	err := c.cc.Invoke(ctx, "/relayer.RelayerRpc/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayerRpcServer is the server API for RelayerRpc service.
type RelayerRpcServer interface {
	Withdraw(context.Context, *WithdrawRequest) (*WithdrawResponse, error)
}

// UnimplementedRelayerRpcServer can be embedded to have forward compatible implementations.
type UnimplementedRelayerRpcServer struct {
}

func (*UnimplementedRelayerRpcServer) Withdraw(ctx context.Context, req *WithdrawRequest) (*WithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}

func RegisterRelayerRpcServer(s *grpc.Server, srv RelayerRpcServer) {
	s.RegisterService(&_RelayerRpc_serviceDesc, srv)
}

func _RelayerRpc_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerRpcServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/relayer.RelayerRpc/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerRpcServer).Withdraw(ctx, req.(*WithdrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RelayerRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "relayer.RelayerRpc",
	HandlerType: (*RelayerRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Withdraw",
			Handler:    _RelayerRpc_Withdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relayer.proto",
}
